# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Open_button = QtWidgets.QPushButton(self.centralwidget)
        self.Open_button.setGeometry(QtCore.QRect(30, 30, 89, 25))
        self.Open_button.setObjectName("Open_button")
        self.pdf_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.pdf_browser.setGeometry(QtCore.QRect(30, 80, 751, 471))
        self.pdf_browser.setObjectName("pdf_browser")
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setEnabled(False)
        self.search_button.setGeometry(QtCore.QRect(180, 30, 89, 25))
        self.search_button.setObjectName("search_button")
        self.search_text = QtWidgets.QLineEdit(self.centralwidget)
        self.search_text.setEnabled(False)
        self.search_text.setGeometry(QtCore.QRect(290, 30, 281, 25))
        self.search_text.setObjectName("search_text")
        self.amount_text = QtWidgets.QLineEdit(self.centralwidget)
        self.amount_text.setGeometry(QtCore.QRect(610, 30, 113, 25))
        self.amount_text.setObjectName("amount_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Open_button.setText(_translate("MainWindow", "Open PDF"))
        self.search_button.setText(_translate("MainWindow", "search"))
